#!/usr/bin/env python3
"""A12.1 — ORDER-AUTHORIZED PROMOTION CONTROLLER (audit round-2 #11/#12).

The controller is the ONLY production route from a validated acquisition
pair to a locked capability. It derives everything itself:

    completed_cells()  ->  authorize_event()  ->  derived namespace
                       ->  derived T0/T1 evidence  ->  receipt  ->  lock

The operator supplies a (block, family, universe) triple and nothing else:
no chain tips, no cell ids, no output directory, no artifact list. The
candidate capability is causally rooted in the universe's OWN acquisition
evidence — the content-addressed `solver_py` payload of the T0 run, checked
byte-for-byte against T1 — so copying another universe's artifact into this
universe's capability directory cannot make it lockable (the receipt names
exactly which artifact hashes may be locked, and the lock writer locks only
those).

Frozen protocol rule (auditor ruling, A12): T0 produces candidate K,
content-addressed and frozen; T1 may build a new local adapter and may
invoke/test K, but may NOT alter K's semantic core or artifact bytes. T1
SHIP -> promotion; T1 failure -> no promotion.

A12d slice D3 (auditor A12d.5): the consumer-visible capability bytes
are MINIMAL and opaque. The minted `manifest.json` carries EXACTLY the
keys {artifacts, capability_id, candidate_sha256, family, interface,
producer_contract, usage, version} — `block` and `universe` are REMOVED
(they stay auditor-side in the lock, receipt, chain, and run manifest).
`capability_id` in the consumer manifest is an OPAQUE alias,
"cap-" + sha256(canonical_json({"candidate_sha256",
"producer_contract", "version"}))[:12] with canonical_json =
json.dumps(obj, sort_keys=True, separators=(",", ":")) — identical
across blocks and universes for identical candidate + contract bytes,
carrying no block letter, no universe letter, no family token, and no
order position. `family` stays only as the benchmark's public
task-category taxonomy (identical across blocks and universes; the
label spells the word "family" plus the category number, e.g.
"family-05", so it carries no namespace token). The canonical
per-universe cell capability id (famNN-BLOCK-UNIVERSE-K) stays
auditor-side (lock/receipt/chain/order) and is unchanged there. The
manifest must not explain its own derivation (no provenance in
consumer bytes); the alias rule lives here in code (see
consumer_capability_alias() + consumer_family_label()).

Stdlib only.
"""
import hashlib
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import order  # noqa: E402
import lock as _lock  # noqa: E402
import identity as _identity  # noqa: E402
import t4_ids as _t4_ids  # noqa: E402
import conformance as _conformance  # noqa: E402

GRADES = ("estimand", "harness-validation")
CANDIDATE_FIELD = "execution_payload.solver_py"
ARTIFACT_NAMES = ("engine.py", "manifest.json", "adapter_notes.md")

# The engine template is harness bytes (covered by EXECUTION-LOCK). It is
# deterministic given the candidate source: the adapter materializes the
# capability inputs described by field_map+records into a directory, writes
# the EXACT candidate bytes to candidate.py, and runs them as a subprocess
# with their own argv — exactly as acquisition did:
#
#     python candidate.py <materialized_input_dir> <output_path>
#
# A12b.3: one ABI across acquisition, T1 validation, and downstream reuse.
# No exec(), no solve() requirement: an argv-ABI candidate that SHIPped T0
# (top-level sys.argv script, no solve function) executes byte-identically
# here. The materialized bytes are hash-verified against the locked
# candidate sha256 before execution (fail closed).
ENGINE_TEMPLATE = '''#!/usr/bin/env python3
"""fam-C capability engine — generated by harness/promotion.py (A12.1).

Interface (frozen): engine.py <field_map.json> <records.json> <OUTPUT.json>

The capability below is the content-addressed acquisition candidate
sha256 __CANDIDATE_SHA256__.
The adapter is harness plumbing; it does not contain task knowledge.
"""
import hashlib
import json
import os
import subprocess
import sys

CANDIDATE_SHA256 = "__CANDIDATE_SHA256__"
CANDIDATE_SOURCE = __CANDIDATE_SOURCE__


def _render(fmap, records, dest):
    files = (fmap or {}).get("files") or {}
    for rel, spec in sorted(files.items()):
        path = os.path.join(dest, rel)
        os.makedirs(os.path.dirname(path) or dest, exist_ok=True)
        if isinstance(spec, str):
            text = spec
        elif "template" in spec:
            tmpl = spec["template"]
            if spec.get("repeat") == "records":
                text = "".join(tmpl.format(**{str(k): v for k, v in rec.items()})
                               for rec in records)
            else:
                text = tmpl.format(**{str(k): v for k, v in (fmap or {}).items()})
        elif "literal" in spec:
            text = spec["literal"]
        else:
            text = ""
        with open(path, "w") as f:
            f.write(text)


def main():
    fmap = json.load(open(sys.argv[1]))
    records = json.load(open(sys.argv[2]))
    out_path = os.path.abspath(sys.argv[3])
    indir = os.path.join(os.path.dirname(out_path), "_candidate_input")
    os.makedirs(indir, exist_ok=True)
    _render(fmap, records, indir)
    cand_path = os.path.join(indir, "candidate.py")
    with open(cand_path, "w") as f:
        f.write(CANDIDATE_SOURCE)
    digest = hashlib.sha256(open(cand_path, "rb").read()).hexdigest()
    if digest != CANDIDATE_SHA256:
        raise SystemExit(
            "CANDIDATE-CONTRACT-DENY: materialized candidate bytes "
            f"{digest[:12]} != locked candidate {CANDIDATE_SHA256[:12]}")
    p = subprocess.run([sys.executable, cand_path, indir, out_path])
    if p.returncode != 0:
        raise SystemExit(p.returncode)
    if not os.path.exists(out_path):
        raise SystemExit("CANDIDATE-CONTRACT-DENY: candidate wrote no output")


if __name__ == "__main__":
    main()
'''


def _sha_bytes(b):
    return hashlib.sha256(b).hexdigest()


def _sha_file(p):
    with open(p, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _canon(obj):
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


def consumer_capability_alias(candidate_sha256, producer_contract, version):
    """Opaque consumer capability alias (A12d slice D3 / A12d.5).

    "cap-" + sha256(canonical_json({"candidate_sha256",
    "producer_contract", "version"}))[:12] with canonical_json =
    json.dumps(obj, sort_keys=True, separators=(",", ":")). Identical
    across blocks and universes for identical candidate + contract
    bytes; carries no block letter, no universe letter, no family
    token, and no order position. The canonical cell capability id
    stays auditor-side and is unchanged there.
    """
    payload = {"candidate_sha256": candidate_sha256,
               "producer_contract": producer_contract,
               "version": version}
    blob = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return "cap-" + hashlib.sha256(blob.encode()).hexdigest()[:12]


def consumer_family_label(family):
    """Consumer-visible family taxonomy label (A12d slice D3 / A12d.5).

    The benchmark's public task-category taxonomy, identical across
    blocks and universes and encoding no arm/order information. The
    label spells the word "family" plus the category number (e.g.
    auditor family "fam05" -> consumer label "family-05") so the
    consumer bytes carry no namespace token (the auditor-side
    "fam0N" prefix would collide with one).
    """
    digits = family[3:] if family.startswith("fam") else family
    return "family-" + digits


def _read_json(p):
    with open(p) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# producer-declared capability contract (A12b.1/AC6b: the producer's own
# arrival payload is the ONLY source of the promoted contract)
# ---------------------------------------------------------------------------
#
# NOTE: there is deliberately NO hidden-contract parser in this module.
# A prior revision derived the receipt/lock contract by parsing the
# frozen families/<family>/K.md here; that synthesis path is DELETED.
# Hidden K.md is read NOWHERE in the promotion path — not in this
# controller, not in the order.py governance cross-checks (those compare
# the receipt against the T0 arrival's own declaration, verbatim), never
# into consumer artifacts. Test-support producer stand-ins carry their
# own independently written contract text
# (harness/tests/fixture_modelrun.py).

_ATOMIC_RE = re.compile(r"^[a-z0-9_.-]+$")


def _producer_contract(t0_run_dir):
    """Read the PRODUCER-declared capability contract from the T0 arrival's
    own `execution_payload.capability_contract` ({semantic_core,
    preconditions, limitations}) — the SOLE source of the promoted
    contract text (A12b.1/AC6b). Fail closed when absent or malformed.
    Returns (semantic_core, preconditions, limitations) with the
    declaration bytes copied exactly (no normalization: the governance
    validator compares them verbatim). This function never touches K.md.

    A12d slice D7 (auditor D6-post P0): the producer contract has ONE
    schema and ONE key. `execution_payload.capability_contract` must be
    a dict with EXACTLY the top-level keys {semantic_core,
    preconditions, limitations} — the undocumented `payload["contract"]`
    alias is DELETED (no alias, no backward compatibility: no live
    promotion exists), a missing key and an extra key are each refused
    with a PROMOTION-DENY naming the key literally, and nothing is ever
    silently dropped. The structural v5 rules below are unchanged, and
    an unknown atomic token still promotes verbatim (D6 semantics).

    A12d slice D6 (auditor D5-post P0, kept): promotion validates
    STRUCTURAL shape only and preserves arbitrary atomic producer tokens
    verbatim. Both lists MAY be empty. Each precondition must be an
    object with EXACTLY the key `requires_all` carrying a list of >=1
    atomic tokens (`^[a-z0-9_.-]+$`, no duplicates). A bare-string
    precondition, the retired `requires` key, an object with any other
    key, an empty list, a non-atomic token, or a duplicate is refused
    with a named PROMOTION-DENY (no backward compatibility, never
    silent). An unknown atom is NOT a promotion defect: it promotes
    verbatim and is judged auditor-side by conformance as
    non-conformance-bearing. Promotion never loads, reads, or consults
    the recognition set.
    """
    try:
        arrival = _read_json(os.path.join(t0_run_dir, "arrival.json"))
    except (ValueError, OSError) as e:
        raise PermissionError(f"PROMOTION-DENY T0 arrival unreadable: {e}")
    payload = _arrival_payload(arrival)
    declared = payload.get("capability_contract")
    if not isinstance(declared, dict):
        raise PermissionError(
            "PROMOTION-DENY T0 arrival declares no producer capability "
            "contract (execution_payload.capability_contract "
            "{semantic_core, preconditions, limitations} is required; the "
            "promoted contract is producer-authored, never synthesized)")
    _want = {"semantic_core", "preconditions", "limitations"}
    _got = set(declared)
    _missing = sorted(_want - _got)
    if _missing:
        raise PermissionError(
            "PROMOTION-DENY producer capability contract is missing the "
            f"required top-level key {_missing[0]!r} (the exact three-key "
            "shape {semantic_core, preconditions, limitations} is "
            "required; nothing is defaulted, nothing is dropped)")
    _extra = sorted(_got - _want)
    if _extra:
        raise PermissionError(
            "PROMOTION-DENY producer capability contract carries an "
            f"extra top-level key {_extra[0]!r} (the exact three-key "
            "shape {semantic_core, preconditions, limitations} is "
            "required; unlisted keys are refused, never silently dropped)")
    core = declared.get("semantic_core")
    if "preconditions" not in declared:
        raise PermissionError(
            "PROMOTION-DENY producer capability contract declares no "
            "preconditions list (the v4 shape requires the "
            "preconditions, limitations, and semantic_core keys to be "
            "present; preconditions may be an empty list)")
    if "limitations" not in declared:
        raise PermissionError(
            "PROMOTION-DENY producer capability contract declares no "
            "limitations list (the v4 shape requires the preconditions, "
            "limitations, and semantic_core keys to be present; "
            "limitations may be an empty list)")
    pre = declared.get("preconditions")
    lim = declared.get("limitations")
    if not isinstance(core, str) or not core.strip():
        raise PermissionError(
            "PROMOTION-DENY producer capability contract has an empty "
            "semantic_core")
    if not isinstance(pre, list):
        raise PermissionError(
            "PROMOTION-DENY producer capability contract preconditions "
            "must be an atomic-conjunction-v5 shape list of "
            "{\"requires_all\": [atomic tokens]} objects "
            "(possibly empty)")
    for entry in pre:
        if isinstance(entry, str):
            raise PermissionError(
                "PROMOTION-DENY producer capability contract carries a "
                "bare-string precondition "
                f"{entry[:60]!r}: the atomic-conjunction-v5 shape "
                "requires {\"requires_all\": [atomic tokens]} objects "
                "(a bare string cannot carry the structural "
                "conjunction, so a conditional clause could smuggle a "
                "branching claim past conformance)")
        if not isinstance(entry, dict) or set(entry) != {"requires_all"}:
            raise PermissionError(
                "PROMOTION-DENY producer capability contract carries a "
                f"malformed precondition {str(entry)[:80]!r}: the "
                "atomic-conjunction-v5 shape is exactly "
                "{\"requires_all\": [atomic tokens]} (the retired "
                "\"requires\" key and every unknown key are refused)")
        _toks = entry.get("requires_all")
        if not isinstance(_toks, list) or not _toks:
            raise PermissionError(
                "PROMOTION-DENY producer capability contract carries a "
                "precondition with an empty requires_all list (each "
                "{\"requires_all\": [tokens]} must name >=1 atomic "
                "applicability token)")
        for _tok in _toks:
            if not isinstance(_tok, str) or not _ATOMIC_RE.match(_tok):
                raise PermissionError(
                    "PROMOTION-DENY producer capability contract "
                    "carries a non-atomic requires_all token "
                    f"{_tok!r}: the atomic-conjunction-v5 shape admits "
                    "only ^[a-z0-9_.-]+$ tokens (a conditional clause "
                    "is structurally unrepresentable as conformance "
                    "evidence)")
            # A12d slice D6: NO vocabulary gate here — an arbitrary
            # atomic token (even one the auditor-side recognition set
            # has never seen) promotes verbatim; conformance judges it
            # non-bearing auditor-side.
        if len(set(_toks)) != len(_toks):
            _dup = next(t for t in _toks if _toks.count(t) > 1)
            raise PermissionError(
                "PROMOTION-DENY producer capability contract carries "
                "a duplicate requires_all token "
                f"{_dup!r}: the atomic-conjunction-v5 shape admits no "
                "duplicates")
    if not isinstance(lim, list) or not all(isinstance(x, str) for x in lim):
        raise PermissionError(
            "PROMOTION-DENY producer capability contract limitations must "
            "be a list of strings (possibly empty; free prose, recorded "
            "verbatim, never conformance evidence)")
    return core, [dict(p) for p in pre], list(lim)


def t4_semantic_id(fam_c_dir, family, semantic_core_sha256,
                   evidence_grade):
    """Auditor-side T4 conformance id, resolved through the SINGLE frozen
    governed registry (harness/t4_ids.py) — never a private registry read,
    never a hash-derived fallback. A registered family resolves to its
    frozen id (ratified True, any grade); an unregistered family gets an
    explicitly UNRATIFIED id on harness-validation and refuses on
    estimand; a registry id outside the PREREG frozen set refuses."""
    return _t4_ids.resolve(fam_c_dir, family, semantic_core_sha256,
                           evidence_grade)


# ---------------------------------------------------------------------------
# event derivation (the operator never names an event)
# ---------------------------------------------------------------------------

ACQ_SEQUENCE = ("T0", "T1", "PROMOTION", "CAPABILITY_LOCK")


def next_event(fam_c_dir, block, family, universe, freeze_commit=None,
               expansion=None):
    """Return (event, cell, reasons). The event is DERIVED: the first
    acquisition event of this universe that is not yet validated COMPLETE.
    The operator cannot ask for a later event."""
    exp = expansion if expansion is not None else order.load_expansion(fam_c_dir)
    done = order.completed_cells(fam_c_dir, freeze_commit, exp)
    for ev in ACQ_SEQUENCE:
        cell = order.expected_event(exp, block, family, ev, universe)
        if cell is None:
            continue
        if cell["cell_id"] not in done:
            return ev, cell, []
    return None, None, [f"PROMOTION-DENY all acquisition events for "
                        f"{block}/{family}/{universe} are already COMPLETE "
                        f"(no repromotion; locks are write-once)"]


def _authorized_cell(fam_c_dir, cell, freeze_commit=None):
    """authorize_event() with the REAL done-set; returns reasons ([]=ok)."""
    exp = order.load_expansion(fam_c_dir)
    done = order.completed_cells(fam_c_dir, freeze_commit, exp)
    got, reasons = order.authorize_event(exp, cell["block"], cell["family"],
                                         cell["event"], cell["universe"], done)
    if got is None or got["cell_id"] != cell["cell_id"]:
        return reasons or ["ORDER-DENY: authorize_event returned a different "
                           "cell"]
    return reasons


# ---------------------------------------------------------------------------
# acquisition evidence derivation
# ---------------------------------------------------------------------------

def _arrival_payload(arrival):
    return arrival.get("execution_payload") or {}


def _read_chain_links(run_dir):
    """Parse one run's evidence chain into link dicts. The chain itself was
    verified by cell_state() before run_evidence() runs; this reader only
    extracts the committed evidence (fail closed on unreadable chains)."""
    p = os.path.join(run_dir, "EVIDENCE-CHAIN.jsonl")
    if not os.path.isfile(p) or os.path.islink(p):
        raise PermissionError(f"PROMOTION-DENY no evidence chain at {p} "
                              f"(remove/tamper the evaluator link -> deny)")
    try:
        links = [json.loads(line) for line in open(p) if line.strip()]
    except ValueError as e:
        raise PermissionError(f"PROMOTION-DENY evidence chain unparsable "
                              f"at {p}: {e}")
    if not links:
        raise PermissionError(f"PROMOTION-DENY evidence chain empty at {p}")
    return links


def _evaluator_evidence(run_dir, event):
    """Derive evaluator provenance from the VERIFIED evaluator chain link —
    never from duplicated nullable manifest fields. Refuses when the link
    is absent, when any evidence sha is null, or when the terminal grade
    does not bind this evaluator state (remove/tamper -> PROMOTION-DENY)."""
    links = _read_chain_links(run_dir)
    evs = [l for l in links if l.get("kind") == "evaluator"]
    if not evs:
        raise PermissionError(
            f"PROMOTION-DENY {event} chain has no verified evaluator link "
            f"(remove/tamper the evaluator link -> deny)")
    ev = evs[-1]
    pay = ev.get("payload") or {}
    missing = [f for f in ("checker_sha256", "truth_sha256", "output_sha256")
               if not pay.get(f)]
    if missing:
        raise PermissionError(
            f"PROMOTION-DENY {event} evaluator link carries null evidence "
            f"field(s): {', '.join(missing)} (no null evaluator evidence)")
    grades = [l for l in links if l.get("kind") == "grade"]
    if not grades or (grades[-1].get("payload") or {}).get(
            "evaluator_link_hash") != ev.get("link_hash"):
        raise PermissionError(
            f"PROMOTION-DENY {event} terminal grade does not bind the "
            f"evaluator link (chain tamper -> deny)")
    return {"evaluator": pay.get("evaluator"), "verdict": pay.get("verdict"),
            "checker_sha256": pay["checker_sha256"],
            "truth_sha256": pay["truth_sha256"],
            "output_sha256": pay["output_sha256"],
            "checker_returncode": pay.get("checker_returncode"),
            "evaluator_link_hash": ev.get("link_hash"),
            "chain_tip": links[-1].get("link_hash")}


def _identity_evidence(run_dir, manifest, cell):
    """Derive producer identity from the VALIDATED identity record. The
    record is cross-verified against its usage receipt HERE at promotion
    time (a swapped/foreign identity — e.g. a Q identity in a P run —
    breaks the binding -> PROMOTION-DENY), and its current bytes plus the
    echoed model are checked against the model-call link the verified
    chain committed at capture (post-hoc identity/echo edits -> deny)."""
    event = cell["event"]
    receipts = manifest.get("usage_receipts") or []
    if not receipts:
        raise PermissionError(f"PROMOTION-DENY {event} run lists no usage "
                              f"receipt (no producer identity derivable)")
    rcp = os.path.join(run_dir, os.path.basename(receipts[0]))
    idp = os.path.join(run_dir, "identity.json")
    try:
        id_rec = _identity.verify_identity_binding(idp, rcp)
    except (ValueError, OSError) as e:
        raise PermissionError(
            f"PROMOTION-DENY {event} producer identity does not verify "
            f"against its usage receipt (a swapped or foreign identity "
            f"cannot promote): {e}")
    family = manifest.get("identity_prereg_family")
    links = _read_chain_links(run_dir)
    mcs = [l for l in links if l.get("kind") == "model-call"]
    if mcs:
        mc = mcs[0].get("payload") or {}
        if mc.get("identity_sha256") and \
                mc["identity_sha256"] != _sha_file(idp):
            raise PermissionError(
                f"PROMOTION-DENY {event} identity.json bytes differ from "
                f"the identity sha the verified chain committed at capture "
                f"(post-hoc identity edit -> deny)")
        if mc.get("model_echoed") and \
                id_rec.get("model_echoed_model") != mc["model_echoed"]:
            raise PermissionError(
                f"PROMOTION-DENY {event} echoed model "
                f"{id_rec.get('model_echoed_model')!r} != the echo "
                f"{mc['model_echoed']!r} committed at capture (post-hoc "
                f"echo edit -> deny)")
        family = family or mc.get("identity_prereg_family")
    # A12b.7 (AC1b): semantic identity check against the PREREGISTERED lane
    # entry. Bindings alone cannot catch an echo-only rewrite (endpoint,
    # requested id, and request bytes all stay valid), so the echoed model
    # must be one the frozen lane entry actually allows.
    try:
        from run_arm_h1 import LANES as _LANES
    except ImportError as e:
        raise PermissionError(
            f"PROMOTION-DENY {event} lane registry unreadable, cannot "
            f"verify producer identity against the preregistered entry: {e}")
    lane = manifest.get("lane")
    entry = _LANES.get(lane)
    if entry is None:
        raise PermissionError(
            f"PROMOTION-DENY {event} lane {lane!r} has no preregistered "
            f"entry (unknown producer lane -> deny)")
    try:
        _identity.check_against_prereg(idp, {
            "endpoint": entry["base"], "requested_id": entry["model"],
            "acceptable_echoed_ids": entry["echo_acceptable"],
            "family": entry["family"]})
    except (ValueError, OSError, KeyError) as e:
        raise PermissionError(
            f"PROMOTION-DENY {event} producer identity is not the "
            f"preregistered lane-{lane} identity (echo/requested/endpoint "
            f"outside the frozen entry -> deny): {e}")
    family = family or entry["family"]
    return {"source_cell": cell["cell_id"], "lane": manifest.get("lane"),
            "endpoint": id_rec.get("endpoint"),
            "model_requested": id_rec.get("model_requested"),
            "model_echoed": id_rec.get("model_echoed_model"),
            "provider_response_id": id_rec.get("provider_response_id"),
            "provider_response_created": id_rec.get("model_echoed_created"),
            "identity_sha256": _sha_file(idp),
            "request_body_sha256": id_rec.get("request_body_sha256"),
            "messages_sha256": id_rec.get("messages_sha256"),
            "identity_prereg_family": family}


def run_evidence(fam_c_dir, cell, freeze_commit=None):
    """Derive ONE acquisition run's evidence from disk. Every value is read
    from the validated run itself — never supplied by the caller."""
    st = order.cell_state(fam_c_dir, cell, freeze_commit)
    if st["status"] != "COMPLETE":
        raise PermissionError(
            f"PROMOTION-DENY {cell['event']} cell {cell['cell_id']} is not "
            f"validated COMPLETE ({st['status']}: "
            f"{'; '.join(st['reasons'][:2])})")
    d = order.run_dir(fam_c_dir, cell)
    mfp = os.path.join(d, "H1-RUN-MANIFEST.json")
    ap = os.path.join(d, "arrival.json")
    if not (os.path.isfile(mfp) and os.path.isfile(ap)):
        raise PermissionError(f"PROMOTION-DENY {cell['event']} run missing "
                              f"manifest/arrival at {d}")
    mf, arrival = _read_json(mfp), _read_json(ap)
    chain = os.path.join(d, "EVIDENCE-CHAIN.jsonl")
    tip = order._chain_tip(chain)
    decision = arrival.get("decision")
    payload = _arrival_payload(arrival)
    ev = {"cell_id": cell["cell_id"], "event": cell["event"],
          "task": mf.get("task"), "arm": mf.get("arm"),
          "lane": mf.get("lane"), "verdict": mf.get("verdict"),
          "chain_tip": tip, "run_dir": d,
          "manifest_sha256": _sha_file(mfp), "arrival_sha256": _sha_file(ap),
          "decision": decision,
          "task_snapshot_hash": mf.get("context_task_snapshot_hash"),
          # A12b.7: evaluator provenance comes from the VERIFIED evaluator
          # chain link (never nullable manifest fields), and producer
          # identity from the VALIDATED identity record. Both refuse.
          "evaluator": _evaluator_evidence(d, cell["event"]),
          "identity": _identity_evidence(d, mf, cell),
          "solver_py_sha256": (_sha_bytes(payload["solver_py"].encode())
                               if isinstance(payload.get("solver_py"), str)
                               else None)}
    if ev["verdict"] != "ship":
        raise PermissionError(f"PROMOTION-DENY {cell['event']} run "
                              f"{cell['cell_id']} verdict {ev['verdict']!r} "
                              f"!= 'ship'")
    return ev


def _per_cell_evidence(ev):
    """One source cell's promotion evidence (AC4/AC5): flat evaluator shas
    taken from the VERIFIED evaluator chain link (never null, never
    re-derived) and flat identity provenance taken from the VALIDATED
    identity record — plus the full nested blocks for audit depth."""
    ident = ev["identity"]
    evaluator = ev["evaluator"]
    return {
        "cell_id": ev["cell_id"], "task": ev["task"], "lane": ev["lane"],
        "verdict": ev["verdict"], "chain_tip": ev["chain_tip"],
        "manifest_sha256": ev["manifest_sha256"],
        "arrival_sha256": ev["arrival_sha256"], "decision": ev["decision"],
        "checker_sha256": evaluator["checker_sha256"],
        "truth_sha256": evaluator["truth_sha256"],
        "output_sha256": evaluator["output_sha256"],
        "evaluator_link_hash": evaluator["evaluator_link_hash"],
        "requested_model": ident["model_requested"],
        "echoed_model": ident["model_echoed"],
        "provider_response_id": ident["provider_response_id"],
        "identity_sha256": ident["identity_sha256"],
        "evaluator": evaluator, "identity": ident,
    }


def _producer_identity(t0_ev, t1_ev):
    """Derive the promotion receipt's producer identity EXCLUSIVELY from
    the validated T0/T1 identity records: requested model, echoed model,
    provider response id, identity sha, lane, and source cell per
    acquisition event. No operator-supplied builder_identity."""
    out = {"producer": "harness/promotion.py"}
    for tag, ev in (("t0", t0_ev), ("t1", t1_ev)):
        ident = ev["identity"]
        out[tag] = {
            "source_cell": ident["source_cell"], "lane": ident["lane"],
            "endpoint": ident["endpoint"],
            "model_requested": ident["model_requested"],
            "model_echoed": ident["model_echoed"],
            "provider_response_id": ident["provider_response_id"],
            "identity_sha256": ident["identity_sha256"],
            "identity_prereg_family": ident["identity_prereg_family"]}
        out[tag + "_lane"] = ev["lane"]
        out[tag + "_verdict"] = ev["verdict"]
    return out


def _t1_candidate_validation(t1_run_dir, t0_sha):
    """Re-derive the T1 candidate-validation evidence from the committed
    T1 chain (fail closed). A12c D3 + A12d D1-C3: promotion requires
    exactly one candidate-validation event with all eleven fields
    present/non-null, `validated is True`, `validation_verdict == "ship"`,
    `candidate_sha256 == executed_sha256 == T0 arrival candidate sha`,
    and a 64-hex `adapter_sha256` (plus 64-hex candidate-output / checker
    / truth shas and checker_returncode == 0 — the host-side T1 checker
    over CANDIDATE-OUTPUT.json), plus the two input-lineage hashes
    re-derived from the COMMITTED artifacts: the persisted
    CANDIDATE-INPUT-MANIFEST.json file bytes must hash to
    `candidate_input_manifest_sha256` and the manifest's recomputed tree
    hash must equal `candidate_input_tree_sha256` (never trusted from the
    receipt), and the event's `candidate_sha256` must equal the frozen T0
    candidate. Any deviation -> PROMOTION-DENY naming the exact
    missing/mismatched field. The chain must carry EXACTLY ONE such event
    binding the SAME frozen T0 candidate: a T1 with no such event — a
    standalone fresh solve that never saw the candidate — can NEVER
    promote; a T1 whose single event records validated=false promotes as
    a RECORDED NOT-PROMOTED outcome (see promote_universe), never a lock.
    """
    links = _read_chain_links(t1_run_dir)
    evs = [l for l in links if l.get("kind") == "candidate-validation"]
    if len(evs) != 1:
        raise PermissionError(
            f"PROMOTION-DENY T1 chain carries {len(evs)} "
            f"candidate-validation events, need exactly one (a T1 with "
            f"no candidate-validation event never validated the frozen "
            f"candidate and can never promote)")
    pay = evs[-1].get("payload") or {}
    for f in ("candidate_sha256", "executed_sha256", "adapter_sha256",
              "candidate_output_sha256", "checker_sha256", "truth_sha256",
              "checker_returncode", "validation_verdict", "validated",
              "candidate_input_manifest_sha256",
              "candidate_input_tree_sha256"):
        if pay.get(f) is None:
            raise PermissionError(
                f"PROMOTION-DENY T1 candidate-validation event carries "
                f"no {f} (got {pay.get(f)!r}; all eleven keys must be "
                f"present and non-null)")
    for f in ("candidate_sha256", "executed_sha256", "adapter_sha256",
              "candidate_output_sha256", "checker_sha256", "truth_sha256",
              "candidate_input_manifest_sha256",
              "candidate_input_tree_sha256"):
        v = pay.get(f)
        if not (isinstance(v, str) and len(v) == 64):
            raise PermissionError(
                f"PROMOTION-DENY T1 candidate-validation event carries "
                f"no 64-hex {f} (got {v!r})")
        try:
            int(v, 16)
        except ValueError:
            raise PermissionError(
                f"PROMOTION-DENY T1 candidate-validation event carries "
                f"no 64-hex {f} (got {v!r})") from None
    if pay.get("candidate_sha256") != t0_sha:
        raise PermissionError(
            f"PROMOTION-DENY T1 validated candidate "
            f"{pay['candidate_sha256'][:12]} != the frozen T0 candidate "
            f"{t0_sha[:12]} (independent validation must test the SAME "
            f"frozen candidate)")
    if pay.get("executed_sha256") != t0_sha:
        raise PermissionError(
            f"PROMOTION-DENY T1 adapter executed "
            f"{pay['executed_sha256'][:12]} != the frozen T0 candidate "
            f"{t0_sha[:12]} (validation means executing the SAME "
            f"candidate bytes)")
    if pay.get("checker_returncode") != 0:
        raise PermissionError(
            f"PROMOTION-DENY T1 candidate-validation checker_returncode "
            f"{pay.get('checker_returncode')!r} != 0 (the host-side T1 "
            f"checker must pass over CANDIDATE-OUTPUT.json)")
    if pay.get("validation_verdict") != "ship":
        raise PermissionError(
            f"PROMOTION-DENY T1 candidate-validation validation_verdict "
            f"{pay.get('validation_verdict')!r} != 'ship' (the host-side "
            f"T1 checker must pass over CANDIDATE-OUTPUT.json)")
    if pay.get("validated") is not True:
        raise PermissionError(
            f"PROMOTION-DENY T1 candidate-validation event is not "
            f"validated (validated={pay.get('validated')!r})")
    # A12d D1-C3: the input lineage is re-derived from the COMMITTED
    # artifacts (the persisted manifest file + this event), never from the
    # receipt. Any mismatch denies naming the field.
    for _lr in order.candidate_input_lineage_reasons(t1_run_dir, pay):
        raise PermissionError(f"PROMOTION-DENY T1 {_lr}")
    return {"candidate_sha256": pay["candidate_sha256"],
            "executed_sha256": pay["executed_sha256"],
            "adapter_sha256": pay["adapter_sha256"],
            "candidate_output_sha256": pay["candidate_output_sha256"],
            "checker_sha256": pay["checker_sha256"],
            "truth_sha256": pay["truth_sha256"],
            "checker_returncode": pay["checker_returncode"],
            "validation_verdict": pay["validation_verdict"],
            "validated": True,
            "candidate_input_manifest_sha256": pay[
                "candidate_input_manifest_sha256"],
            "candidate_input_tree_sha256": pay[
                "candidate_input_tree_sha256"]}


def derive_candidate(t0_ev, t1_ev, t0_run_dir):
    """The candidate is the T0 arrival's `solver_py` payload, content-
    addressed. T1 must have VALIDATED it: the T1 chain carries exactly one
    candidate-validation event for this same candidate (fail closed — the
    no-declaration path is DELETED; a standalone fresh T1 may still SHIP
    its own cell, but it can never promote). If T1 declares a candidate
    hash in its arrival it must match exactly."""
    ap = os.path.join(t0_run_dir, "arrival.json")
    arrival = _read_json(ap)
    payload = _arrival_payload(arrival)
    src = payload.get("solver_py")
    if not isinstance(src, str) or not src.strip():
        raise PermissionError("PROMOTION-DENY T0 arrival carries no "
                              "execution_payload.solver_py candidate")
    if arrival.get("decision") != "fresh":
        raise PermissionError("PROMOTION-DENY T0 decision "
                              f"{arrival.get('decision')!r} != 'fresh' "
                              "(acquisition must solve fresh)")
    sha = _sha_bytes(src.encode())
    # A12b.2: the fail-closed validation gate — the T1 chain must prove
    # the adapter saw and executed THIS frozen candidate. No event, no
    # promotion (a standalone fresh T1 still SHIPs its cell; SHIP is not
    # promotion).
    t1_dir = t1_ev["run_dir"]
    t1_validation = _t1_candidate_validation(t1_dir, sha)
    declared = None
    t1_arr = _read_json(os.path.join(t1_dir, "arrival.json"))
    t1_payload = _arrival_payload(t1_arr)
    if isinstance(t1_payload.get("candidate_sha256"), str):
        declared = t1_payload["candidate_sha256"]
    if t1_arr.get("decision") == "use_capability":
        if declared is None:
            raise PermissionError("PROMOTION-DENY T1 chose use_capability but "
                                  "declares no candidate_sha256")
        if declared != sha:
            raise PermissionError(
                f"PROMOTION-DENY T1 used candidate {declared[:12]} but T0 "
                f"candidate is {sha[:12]} (independent validation must test "
                f"the SAME frozen candidate)")
    elif declared is not None and declared != sha:
        raise PermissionError("PROMOTION-DENY T1 declares a different "
                              f"candidate {declared[:12]} != T0 {sha[:12]}")
    if t1_ev["task"] == t0_ev["task"]:
        raise PermissionError("PROMOTION-DENY T0 and T1 share one task id; "
                              "promotion requires a distinct task/surface")
    if (t0_ev["task_snapshot_hash"]
            and t0_ev["task_snapshot_hash"] == t1_ev["task_snapshot_hash"]):
        raise PermissionError("PROMOTION-DENY T0 and T1 have identical task "
                              "snapshots; promotion requires a distinct "
                              "task/surface")
    return {"sha256": sha, "source": src, "field": CANDIDATE_FIELD,
            "arrival_sha256": t0_ev["arrival_sha256"],
            "payload_sha256": _sha_bytes(_canon(payload).encode()),
            "t1_used_candidate": t1_arr.get("decision") == "use_capability",
            "t1_decision": t1_arr.get("decision"),
            "t1_validation": t1_validation}


# ---------------------------------------------------------------------------
# artifact minting (deterministic; harness plumbing only)
# ---------------------------------------------------------------------------

def _mint_artifacts(capdir, cand, contract, cell, protocol_sha, exec_sha,
                    version, evidence_grade, t4_id, t4_ratified):
    # A12c slice B (B2/B3): the consumer-visible artifacts are aggressively
    # minimal — capability id, version, candidate hash, interface, the
    # PRODUCER-authored contract, the engine, and adapter-use instructions.
    # Source cells, chain tips, lock hashes, evidence grade, producer
    # identity, auditor T4 ids, conformance fields, timestamps, and every
    # chain/receipt pointer ride the auditor-side promotion receipt and
    # CAPABILITY_LOCK only — never these files. `cell`, `protocol_sha`,
    # `exec_sha`, `version`, `evidence_grade`, `t4_id`, `t4_ratified` are
    # therefore accepted here for signature stability (and `version` IS
    # consumer-visible below) but no provenance beyond the family taxonomy
    # label is written to these artifacts.
    #
    # A12d slice D3 (auditor A12d.5): consumer-minimal bytes. The manifest
    # key set is EXACTLY {artifacts, capability_id, candidate_sha256,
    # family, interface, producer_contract, usage, version} — `block` and
    # `universe` are REMOVED (auditor-side only). `capability_id` is the
    # opaque consumer alias (see consumer_capability_alias()), identical
    # across blocks/universes for identical candidate + contract bytes;
    # `family` is the consumer taxonomy label (see
    # consumer_family_label()), identical across blocks/universes. The
    # producer contract below comes from the SAME T0 arrival declaration
    # the promotion receipt uses (one source of truth).
    core, pre, lim = contract
    _auditor = (protocol_sha, exec_sha, evidence_grade, t4_id, t4_ratified)
    engine = (ENGINE_TEMPLATE
              .replace("__CANDIDATE_SHA256__", cand["sha256"])
              .replace("__CANDIDATE_SOURCE__", repr(cand["source"])))
    interface = ("engine.py <field_map.json> <records.json> <OUTPUT.json>")
    # The producer-authored contract: rooted in THIS universe's own
    # acquisition arrival payload (the T0 declaration the receipt
    # uses), never in hidden auditor text. This exact object lands in
    # the manifest AND feeds the opaque alias (one source of truth).
    pcontract = {"semantic_core": core,
                 "preconditions": list(pre),
                 "limitations": list(lim)}
    alias = consumer_capability_alias(cand["sha256"], pcontract, version)
    flabel = consumer_family_label(cell["family"])
    contract_lines = [f"# {alias} — promoted capability",
                      "",
                      f"candidate sha256: {cand['sha256']}",
                      "",
                      "## interface",
                      "",
                      interface,
                      "",
                      "## producer contract",
                      "",
                      core,
                      ""]
    contract_lines.append("preconditions:")
    # A12d slice D6: preconditions are v5 {"requires_all": [tokens]}
    # objects — the notes render the producer's token list joined by
    # spaces (never the dict repr), exactly as earlier notes rendered
    # the requires text.
    contract_lines.extend(f"- {' '.join(p['requires_all'])}" for p in pre)
    contract_lines.append("limitations:"
                          if lim else "limitations: none declared")
    contract_lines.extend(f"- {x}" for x in lim)
    contract_lines.extend([
        "",
        "## use",
        "",
        "Run `python3 engine.py <field_map.json> <records.json> "
        "<OUTPUT.json>`: the field map describes the capability inputs, "
        "the records file carries the input records, and the engine "
        "writes its result object to the output path. "
        "Do not modify engine.py."])
    notes = "\n".join(contract_lines) + "\n"
    manifest = {
        "capability_id": alias, "version": version,
        "family": flabel,
        "candidate_sha256": cand["sha256"],
        "interface": interface,
        # The producer-authored contract: rooted in THIS universe's own
        # acquisition arrival payload (the T0 declaration the receipt
        # uses), never in hidden auditor text.
        "producer_contract": pcontract,
        "usage": ("Invoke the frozen engine as `python3 engine.py "
                  "<field_map.json> <records.json> <OUTPUT.json>`: the "
                  "field map describes the capability inputs, the records "
                  "file carries the input records, and the engine writes "
                  "its result object to the output path. The producer "
                  "contract above states what the capability does and "
                  "when it applies; do not modify engine.py.")}
    for name, text in (("engine.py", engine), ("adapter_notes.md", notes)):
        p = os.path.join(capdir, name)
        if os.path.exists(p):
            if open(p).read() != text:
                raise PermissionError(f"PROMOTION-DENY artifact {name} "
                                      f"already exists with different bytes")
        else:
            with open(p, "w") as f:
                f.write(text)
    # manifest.json records the hashes of its siblings (not itself)
    manifest["artifacts"] = {n: _sha_file(os.path.join(capdir, n))
                             for n in ("engine.py", "adapter_notes.md")}
    mp = os.path.join(capdir, "manifest.json")
    with open(mp, "w") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
    return {n: _sha_file(os.path.join(capdir, n)) for n in ARTIFACT_NAMES}


# ---------------------------------------------------------------------------
# the two authorized events
# ---------------------------------------------------------------------------

def _lock_shas(fam_c_dir):
    out = {}
    for key, name in (("protocol_lock_sha256", "PROTOCOL-LOCK.json"),
                      ("execution_lock_sha256", "EXECUTION-LOCK.json")):
        p = os.path.join(fam_c_dir, name)
        if not os.path.isfile(p):
            raise PermissionError(f"PROMOTION-DENY frozen {name} absent")
        out[key] = _sha_file(p)
    return out


def promote_universe(fam_c_dir, block, family, universe, freeze_commit=None,
                     evidence_grade="estimand", version="1.0.0",
                     builder_identity=None):
    """Run the PROMOTION event for one universe. Refuses unless PROMOTION is
    the derived next authorized event."""
    event, cell, reasons = next_event(fam_c_dir, block, family, universe,
                                      freeze_commit)
    if reasons:
        raise PermissionError(reasons[0])
    if event != "PROMOTION":
        raise PermissionError(
            f"PROMOTION-DENY {block}/{family}/{universe} next authorized "
            f"event is {event}, not PROMOTION (the controller derives the "
            f"event; operators never choose one)")
    reasons = _authorized_cell(fam_c_dir, cell, freeze_commit)
    if reasons:
        raise PermissionError(reasons[0])
    if evidence_grade not in GRADES:
        raise ValueError(f"PROMOTION-DENY evidence_grade {evidence_grade!r} "
                         f"not in {list(GRADES)}")
    exp = order.load_expansion(fam_c_dir)
    t0 = order.expected_event(exp, block, family, "T0", universe)
    t1 = order.expected_event(exp, block, family, "T1", universe)
    if t0 is None or t1 is None:
        raise PermissionError("PROMOTION-DENY order has no T0/T1 pair for "
                              f"{block}/{family}/{universe}")
    if evidence_grade == "estimand" and builder_identity is not None:
        raise PermissionError(
            "PROMOTION-DENY estimand promotion derives producer identity "
            "exclusively from the validated T0/T1 identity records (no "
            "operator-supplied builder_identity)")
    # A12d D1-B3: a T1 whose candidate validation FAILED still completed
    # its cell — the failed acquisition is a RECORDED terminal outcome,
    # not a deadlock: the controller records PROMOTION-OUTCOME.json and
    # then REFUSES with a clean PROMOTION-DENY (never a lock). Anything
    # else (no event, several events, an unreadable chain, an event that
    # does not bind the frozen candidate) falls through to the normal
    # path, which denies as before.
    _failed, _cause = order.acquisition_failed(fam_c_dir, block, family,
                                               universe)
    if _failed:
        _t1_dir = order.run_dir(fam_c_dir, t1)
        _t0_dir = order.run_dir(fam_c_dir, t0)
        try:
            _t0_arr = _read_json(os.path.join(_t0_dir, "arrival.json"))
            _t0_src = (_t0_arr.get("execution_payload") or {}).get(
                "solver_py")
            _frozen = (_sha_bytes(_t0_src.encode())
                       if isinstance(_t0_src, str) and _t0_src.strip()
                       else None)
        except (ValueError, OSError):
            _frozen = None
        if _frozen is None:
            raise PermissionError(
                "PROMOTION-DENY T0 arrival carries no frozen candidate "
                "(failed-acquisition outcome not recordable)")
        _cap = order.capability_dir(fam_c_dir, block, universe, family)
        if os.path.exists(os.path.join(_cap, "CAPABILITY_LOCK.json")):
            raise PermissionError(
                "PROMOTION-DENY universe "
                f"{block}/{family}/{universe} has a CAPABILITY_LOCK but "
                f"its T1 candidate validation failed ({_cause}; no lock "
                f"may exist for a failed acquisition)")
        _t0_tip = order._chain_tip(os.path.join(_t0_dir,
                                                "EVIDENCE-CHAIN.jsonl"))
        _t1_tip = order._chain_tip(os.path.join(_t1_dir,
                                                "EVIDENCE-CHAIN.jsonl"))
        _op = order.emit_promotion_outcome(fam_c_dir, cell, _t0_tip,
                                           _t1_tip, _frozen)
        raise PermissionError(
            f"PROMOTION-DENY universe {block}/{family}/{universe} T1 "
            f"candidate validation failed ({_cause}): promotion is "
            f"NOT-PROMOTED (terminal outcome recorded at {_op}), no "
            f"CAPABILITY_LOCK may exist for it, and every downstream "
            f"cell of that universe is NOT-EVALUABLE (no retry: the "
            f"failed validation is an experimental outcome)")
    t0_ev = run_evidence(fam_c_dir, t0, freeze_commit)
    t1_ev = run_evidence(fam_c_dir, t1, freeze_commit)
    producer_identity = _producer_identity(t0_ev, t1_ev)
    cand = derive_candidate(t0_ev, t1_ev, t0_ev["run_dir"])
    # A12b.1/AC6b: the promoted contract is authored by the PRODUCER — it
    # is read from the T0 arrival's own `capability_contract` declaration,
    # never synthesized from hidden K.md (which nothing in the promotion
    # path reads).
    contract = _producer_contract(t0_ev["run_dir"])
    core_sha = _sha_bytes(contract[0].encode())
    t4_id, t4_ratified = t4_semantic_id(fam_c_dir, cell["family"],
                                        core_sha, evidence_grade)
    # A12c slice C2 (auditor P0 #6), A12d slice D5 (auditor D4-post
    # P0): the frozen structural requires_all->T4-id conformance
    # bridge. The lock records the producer's ACTUAL contract plus the
    # derived verdict — derived HERE mechanically from the
    # producer-declared contract through the SINGLE governed
    # implementation (harness/conformance.py over the frozen
    # T4-CONFORMANCE.json map, never by copying hidden K.md text: this
    # controller has no hidden-contract reader by design, and the
    # conformance check reads the lock only). Conformance consults ONLY
    # the structural preconditions[*].requires_all token lists: an
    # unrelated token list (e.g. ['python', '3']) — and every
    # limitation, always — leaves the T4 non-discriminating, because
    # only a requires_all list naming the T4's applicability condition
    # (a frozen predicate match over an admissible atomic token list)
    # supports the id.
    declared_limitations_present = bool(contract[2])
    cmap = _conformance.load(fam_c_dir)
    # A12d slice D6 (auditor D5-post P0): NO vocabulary gate — the
    # contract above already survived structural validation (arbitrary
    # atomic tokens preserved verbatim). The auditor-side recognition
    # set is consulted ONLY inside conformance.verdict() below, which
    # marks unknown-atom preconditions non-conformance-bearing; it
    # never denies promotion. This controller does not read the
    # recognition set at all.
    cverdict = _conformance.verdict(
        cell["family"],
        [p["requires_all"] for p in contract[1]], cmap,
        limitations=contract[2])
    non_discriminating = cverdict["non_discriminating"]
    conformance_cause = cverdict["conformance_cause"]
    supported_t4_ids = cverdict["supported_t4_ids"]
    conformance_map_sha256 = cverdict["conformance_map_sha256"]
    shas = _lock_shas(fam_c_dir)
    capdir = order.ensure_namespace(fam_c_dir, block, universe, family,
                                    tail=("capability",))
    cell = dict(cell)
    cell["source_cells"] = {"T0": t0_ev["cell_id"], "T1": t1_ev["cell_id"]}
    cell["acquisition_chain_tips"] = {"T0": t0_ev["chain_tip"],
                                      "T1": t1_ev["chain_tip"]}
    if cell["source_cells"]["T0"] == cell["source_cells"]["T1"]:
        raise PermissionError("PROMOTION-DENY identical source cells")
    arts = _mint_artifacts(capdir, cand, contract, cell,
                           shas["protocol_lock_sha256"],
                           shas["execution_lock_sha256"], version,
                           evidence_grade, t4_id, t4_ratified)
    exp_sha = _sha_file(os.path.join(fam_c_dir, "ORDER-EXPANSION.json"))
    done = order.completed_cells(fam_c_dir, freeze_commit, exp)
    provenance = {
        "version": version,
        "acquisition_chain_tips": dict(cell["acquisition_chain_tips"]),
        "source_cells": dict(cell["source_cells"]),
        "candidate": {k: cand[k] for k in ("sha256", "field",
                                           "arrival_sha256", "payload_sha256",
                                           "t1_used_candidate", "t1_decision",
                                           "t1_validation")},
        "artifacts": arts,
        "semantic_core": contract[0],
        "semantic_core_sha256": core_sha,
        "preconditions": contract[1], "limitations": contract[2],
        "declared_limitations_present": declared_limitations_present,
        "non_discriminating": non_discriminating,
        "conformance_cause": conformance_cause,
        "supported_t4_ids": supported_t4_ids,
        "conformance_map_sha256": conformance_map_sha256,
        "t4_semantic_id": t4_id, "t4_ratified": t4_ratified,
        "evidence_grade": evidence_grade,
        "producer_identity": producer_identity,
        "protocol_lock_sha256": shas["protocol_lock_sha256"],
        "execution_lock_sha256": shas["execution_lock_sha256"],
        "authorization": {
            "order_sha256": exp_sha, "event_index": cell["index"],
            "done_cells_at_emit": sorted(done),
            "event": "PROMOTION"},
        "t0_evidence": _per_cell_evidence(t0_ev),
        "t1_evidence": _per_cell_evidence(t1_ev),
    }
    rp = order.emit_promotion_receipt(fam_c_dir, cell,
                                      cell["acquisition_chain_tips"]["T0"],
                                      cell["acquisition_chain_tips"]["T1"],
                                      builder_identity=provenance[
                                          "producer_identity"],
                                      provenance=provenance)
    return {"event": "PROMOTION", "cell_id": cell["cell_id"],
            "receipt": rp, "receipt_sha256": _sha_file(rp),
            "capability_dir": capdir, "artifacts": arts,
            "candidate_sha256": cand["sha256"],
            "t4_semantic_id": t4_id, "t4_ratified": t4_ratified,
            "evidence_grade": evidence_grade}


def lock_universe(fam_c_dir, block, family, universe, freeze_commit=None,
                  evidence_grade=None, builder_identity=None):
    """Run the CAPABILITY_LOCK event for one universe. The lock may only
    name the artifact hashes recorded in the validated PROMOTION receipt."""
    event, cell, reasons = next_event(fam_c_dir, block, family, universe,
                                      freeze_commit)
    if reasons:
        raise PermissionError(reasons[0])
    if event != "CAPABILITY_LOCK":
        raise PermissionError(
            f"LOCK-DENY {block}/{family}/{universe} next authorized event is "
            f"{event}, not CAPABILITY_LOCK")
    reasons = _authorized_cell(fam_c_dir, cell, freeze_commit)
    if reasons:
        raise PermissionError(reasons[0])
    exp = order.load_expansion(fam_c_dir)
    prom = order.expected_event(exp, block, family, "PROMOTION", universe)
    if prom is None:
        raise PermissionError("LOCK-DENY order has no PROMOTION cell")
    pst = order.cell_state(fam_c_dir, prom, freeze_commit)
    if pst["status"] != "COMPLETE":
        raise PermissionError("LOCK-DENY PROMOTION not COMPLETE "
                              f"({pst['status']}: {pst['reasons'][:1]})")
    rp = os.path.join(order.run_dir(fam_c_dir, prom), "PROMOTION-RECEIPT.json")
    rec = _read_json(rp)
    arts = rec.get("artifacts")
    if not isinstance(arts, dict) or not arts:
        raise PermissionError("LOCK-DENY promotion receipt names no artifacts "
                              "(lock may only lock receipt-named hashes)")
    capdir = order.capability_dir(fam_c_dir, block, universe, family)
    paths = []
    for name, want in sorted(arts.items()):
        if os.path.basename(name) != name:
            raise PermissionError(f"LOCK-DENY artifact name {name!r} is not a "
                                  f"bare filename")
        p = os.path.join(capdir, name)
        if not os.path.isfile(p) or os.path.islink(p):
            raise PermissionError(f"LOCK-DENY receipt names {name} but it is "
                                  f"absent from {capdir}")
        got = _sha_file(p)
        if got != want:
            raise PermissionError(f"LOCK-DENY receipt artifact {name} hash "
                                  f"{want[:12]} != present {got[:12]}")
        paths.append(p)
    lp = order.emit_capability_lock(fam_c_dir, cell, artifact_paths=paths,
                                    version=rec.get("version", "1.0.0"),
                                    manifest_obj=rec.get("manifest_obj") or {
                                        "capability_id": cell["capability_id"],
                                        "candidate_sha256":
                                            rec["candidate"]["sha256"],
                                        "source_cells": rec["source_cells"],
                                        "semantic_core_sha256":
                                            rec["semantic_core_sha256"],
                                        "artifacts": arts},
                                    training_receipts=[rec["source_cells"]["T0"],
                                                       rec["source_cells"]["T1"]],
                                    builder_identity=rec.get(
                                        "producer_identity") or {},
                                    receipt=rec, receipt_path=rp)
    return {"event": "CAPABILITY_LOCK", "cell_id": cell["cell_id"],
            "lock": lp, "lock_sha256": _sha_file(lp), "artifacts": arts,
            "capability_dir": capdir}


def advance(fam_c_dir, block, family, universe, freeze_commit=None,
            evidence_grade="estimand", version="1.0.0",
            builder_identity=None):
    """Derive the next authorized acquisition event for this universe and
    execute it if it is a governance event. T0/T1 are refused here: they are
    model calls and belong to the acquisition executor (A12.0-d)."""
    event, cell, reasons = next_event(fam_c_dir, block, family, universe,
                                      freeze_commit)
    if reasons:
        raise PermissionError(reasons[0])
    if event == "PROMOTION":
        return promote_universe(fam_c_dir, block, family, universe,
                                freeze_commit, evidence_grade, version,
                                builder_identity)
    if event == "CAPABILITY_LOCK":
        return lock_universe(fam_c_dir, block, family, universe,
                             freeze_commit, evidence_grade, builder_identity)
    raise PermissionError(
        f"ACQUISITION-REQUIRED: {block}/{family}/{universe} next authorized "
        f"event is {event} ({cell['cell_id']}); run it through the "
        f"acquisition executor, not the governance controller")


def main(argv):
    import argparse
    ap = argparse.ArgumentParser(description="A12.1 order-authorized "
                                             "promotion/lock controller")
    ap.add_argument("--fam-c-dir", required=True)
    ap.add_argument("--block", required=True)
    ap.add_argument("--family", required=True)
    ap.add_argument("--universe", required=True)
    ap.add_argument("--freeze-commit")
    ap.add_argument("--evidence-grade", default="estimand", choices=GRADES)
    ap.add_argument("--version", default="1.0.0")
    a = ap.parse_args(argv)
    try:
        out = advance(a.fam_c_dir, a.block, a.family, a.universe,
                      a.freeze_commit, a.evidence_grade, a.version)
    except (PermissionError, ValueError) as e:
        print(f"CONTROLLER-REFUSED: {e}")
        return 2
    print(json.dumps(out, indent=1, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
